var importNodes =[
{"name":"node.journey-intro.0","group":1, "num":0},
{"name":"node.ballooniana","group":1, "num":1},
{"name":"node.balloon-crash-snuffbox","group":1, "num":2},
{"name":"node.apollo-10-test","group":1, "num":3},
{"name":"node.newcomen-engine","group":1, "num":4},
{"name":"node.thomas-wright-orrery","group":1, "num":5},
{"name":"node.air-pump","group":1, "num":6},
{"name":"node.electrical-cylinder","group":1, "num":7},
{"name":"node.phrenological-heads","group":1, "num":8},
{"name":"node.great-exhibition-peep-show","group":1, "num":9},
{"name":"node.apollo-10","group":1, "num":10},
{"name":"node.science-museum","group":1, "num":11},
{"name":"node.mouse-trap-camera","group":1, "num":12},
{"name":"node.journey-intro.1","group":1, "num":13},
{"name":"node.magic-lantern","group":1, "num":14},
{"name":"node.wax-cylinder","group":1, "num":15},
{"name":"node.pyrophone","group":1, "num":16},
{"name":"node.maths-puzzles","group":1, "num":17},
{"name":"node.apple-1","group":1, "num":18},
{"name":"node.pilot-ace","group":1, "num":19},
{"name":"node.cybernetic-tortoise","group":1, "num":20},
{"name":"node.oramics-machine","group":1, "num":21},
{"name":"node.stylophone","group":1, "num":22},
{"name":"node.vcs3","group":1, "num":23},
{"name":"node.hookes-universal-joint","group":1, "num":24},
{"name":"node.hookes-microscope","group":1, "num":25},
{"name":"node.moon-globe","group":1, "num":26},
{"name":"node.trevithick-model-engine","group":1, "num":27},
{"name":"node.stephensons-rocket","group":1, "num":28},
{"name":"node.enigma-machine","group":1, "num":29},
{"name":"node.edison-lightbulb","group":1, "num":30},
{"name":"node.geissler-tubes","group":1, "num":31},
{"name":"node.ipad","group":1, "num":32},
{"name":"node.zeotrope","group":1, "num":33},
{"name":"node.first-colour-tv","group":1, "num":34},
{"name":"node.silver-microscope","group":1, "num":35},
{"name":"node.wollastons-crystal-models","group":1, "num":36},
 ];
var importPaths = [
{"source":5,"target":26,"value":0,"name":"look-to-the-stars"},
{"source":26,"target":10,"value":0,"name":"look-to-the-stars"},
{"source":13,"target":9,"value":1,"name":"science-at-play"},
{"source":9,"target":12,"value":1,"name":"science-at-play"},
{"source":12,"target":33,"value":1,"name":"science-at-play"},
{"source":33,"target":16,"value":1,"name":"science-at-play"},
{"source":16,"target":34,"value":1,"name":"science-at-play"},
{"source":34,"target":21,"value":1,"name":"science-at-play"},
{"source":21,"target":22,"value":1,"name":"science-at-play"},
{"source":22,"target":23,"value":1,"name":"science-at-play"},
{"source":23,"target":18,"value":1,"name":"science-at-play"},
{"source":18,"target":32,"value":1,"name":"science-at-play"},
{"source":29,"target":19,"value":2,"name":"man-machine"},
{"source":19,"target":20,"value":2,"name":"man-machine"},
{"source":25,"target":35,"value":3,"name":"seeing-deeper"},
{"source":35,"target":36,"value":3,"name":"seeing-deeper"},
{"source":0,"target":4,"value":4,"name":"spectacle"},
{"source":4,"target":24,"value":4,"name":"spectacle"},
{"source":24,"target":5,"value":4,"name":"spectacle"},
{"source":5,"target":6,"value":4,"name":"spectacle"},
{"source":6,"target":7,"value":4,"name":"spectacle"},
{"source":7,"target":8,"value":4,"name":"spectacle"},
{"source":8,"target":9,"value":4,"name":"spectacle"},
{"source":9,"target":10,"value":4,"name":"spectacle"},
{"source":10,"target":11,"value":4,"name":"spectacle"},
{"source":18,"target":19,"value":5,"name":"weird-connections"},
{"source":9,"target":11,"value":5,"name":"weird-connections"},
{"source":4,"target":27,"value":6,"name":"steam"},
{"source":27,"target":28,"value":6,"name":"steam"},
 ];
